# Generated by Django 4.1.5 on 2023-01-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('profession_description', models.TextField(max_length=3000)),
                ('profession_image', models.ImageField(upload_to='profession_images/')),
            ],
        ),
    ]
